language: node_js
node_js:
- "7"
services:
- postgresql
before_script:
  - psql -c 'create database test;' -U postgres
  - sequelize db:migrate
env:
	- SECRET=ARSENAL
  global:
    - export NODE_ENV=test
script:
- npm install
- npm test
- npm run coverage
after_success: 'npm run coveralls'