language: node_js
node_js:
- "7"
services:
- postgresql
before_script:
  - psql -c 'create database test;' -U postgres
  - sequelize db:migrate
  - ./cc-test-reporter before-build
env:
  global:
  - CC_TEST_REPORTER_ID=e632d4800db652622767827eace0a9f2aa8353173956696a7dd635936ec456c8
  - export NODE_ENV=test
  - SECRET=ARSENAL
script:
- npm install
- npm test
- npm run coverage
after_script:
- ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
after_success: 'npm run coveralls'