language: node_js
node_js:
- "8"
services:
- postgresql
before_script:
  - psql -c 'create database test;' -U postgres
  - sequelize db:migrate
env:
  global:
    - CC_TEST_REPORTER_ID=06e5cd10a0ad068c1ee97e1ff4ea4c35fa2ba46853828ecb3983236a34ada53b
    - export NODE_ENV=test
    - SECRET=ARSENAL
script:
- npm install
- npm test
- npm run coverage
after_script:
- ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
after_success: 'npm run coveralls'
