export const SET_FETCHING = 'SET_FETCHING';
export const UNSET_FETCHING = 'UNSET_FETCHING';

export const RECIEVE_AUTH = 'RECIEVE_AUTH';
export const AUTH_ERROR = 'AUTH_ERROR';

export const GET_USER_RECIPES = 'GET_USER_RECIPES';
export const GET_USER_RECIPES_ERROR = 'GET_USER_RECIPES_ERROR';
export const GET_ALL_RECIPES = 'GET_ALL_RECIPES';
export const GET_ALL_RECIPES_ERROR = 'GET_ALL_RECIPES_ERROR';
export const GET_ONE_RECIPE = 'GET_ONE_RECIPE';
export const GET_ONE_RECIPE_ERROR = 'GET_ONE_RECIPE_ERROR';
export const EDIT_RECIPE = 'EDIT_RECIPE';
export const EDIT_RECIPE_ERROR = 'EDIT_RECIPE_ERROR';

export const UPLOADING = 'UPLOADING';
export const END_UPLOADING = 'END_UPLOADING';
export const ADD_RECIPE = 'ADD_RECIPE';
export const RECIPE_ERROR = 'RECIPE_ERROR';
export const SIGN_IN_USER = 'SIGN_IN_USER';
export const LOGOUT = 'LOGOUT';

export const UPVOTE_SUCCESS = 'UPVOTE_SUCCESS';
export const UPVOTE_FAILURE = 'UPVOTE_FAILURE';
export const DOWNVOTE_SUCCESS = 'DOWNVOTE_SUCCESS';
export const DOWNVOTE_FAILURE = 'DOWNVOTE_FAILURE';

export const ADD_REVIEW_SUCCESS = 'ADD_REVIEW_SUCCESS';
export const ADD_REVIEW_FAILURE = 'ADD_REVIEW_FAILURE';

export const VIEW_PROFILE = 'VIEW_PROFILE';
export const VIEW_PROFILE_ERROR = 'VIEW_PROFILE_ERROR';
export const EDIT_PROFILE = 'EDIT_PROFILE';
export const EDIT_PROFILE_ERROR = 'EDIT_PROFILE-ERROR';
