export const SET_FETCHING = 'SET_FETCHING';
export const UNSET_FETCHING = 'UNSET_FETCHING';

export const RECIEVE_AUTH = 'RECIEVE_AUTH';
export const AUTH_ERROR = 'AUTH_ERROR';

export const UPLOADING = 'UPLOADING';
export const END_UPLOADING = 'END_UPLOADING';

export const GET_USER_RECIPES = 'GET_USER_RECIPES';
export const GET_USER_RECIPES_ERROR = 'GET_USER_RECIPES_ERROR';

export const GET_ALL_RECIPES = 'GET_ALL_RECIPES';
export const GET_ALL_RECIPES_ERROR = 'GET_ALL_RECIPES_ERROR';
export const GET_FAVOURITE_STATUS = 'GET_FAVOURITE_STATUS';
export const SEARCH_RECIPES = 'SEARCH_RECIPES';
export const SEARCH_RECIPES_ERROR = 'SEARCH_RECIPES_ERROR';
export const GET_TOP_RECIPES = 'GET_TOP_RECIPES';
export const GET_TOP_RECIPES_ERROR = 'GET_TOP_RECIPES_ERROR';

export const GET_ONE_RECIPE = 'GET_ONE_RECIPE';
export const GET_ONE_RECIPE_ERROR = 'GET_ONE_RECIPE_ERROR';

export const EDIT_RECIPE = 'EDIT_RECIPE';
export const EDIT_RECIPE_ERROR = 'EDIT_RECIPE_ERROR';

export const DELETE_RECIPE_ERROR = 'DELETE_RECIPE_ERROR';
export const DELETE_RECIPE = 'DELETE_RECIPE';

export const ADD_RECIPE = 'ADD_RECIPE';
export const RECIPE_ERROR = 'RECIPE_ERROR';

export const SIGN_IN_USER = 'SIGN_IN_USER';
export const LOGOUT = 'LOGOUT';

export const UPVOTE_SUCCESS = 'UPVOTE_SUCCESS';
export const UPVOTE_FAILURE = 'UPVOTE_FAILURE';

export const DOWNVOTE_SUCCESS = 'DOWNVOTE_SUCCESS';
export const DOWNVOTE_FAILURE = 'DOWNVOTE_FAILURE';

export const ADD_FAVOURITES = 'ADD_FAVOURITES';
export const ADD_FAVOURITES_ERROR = 'ADD_FAVOURITES_ERROR';
export const GET_FAVOURITES = 'GET_FAVOURITES';
export const GET_FAVOURITES_ERROR = 'GET_FAVOURITES_ERROR';
export const DELETE_FAVOURITE = 'DELETE_FAVOURITE';
export const DELETE_FAVOURITE_ERROR = 'DELETE_FAVOURITE_ERROR';

export const GET_REVIEW_SUCCESS = 'GET_REVIEW_SUCCESS';
export const GET_REVIEW_FAILURE = 'GET_REVIEW_FAILURE';
export const ADD_REVIEW_SUCCESS = 'ADD_REVIEW_SUCCESS';
export const ADD_REVIEW_FAILURE = 'ADD_REVIEW_FAILURE';

export const VIEW_PROFILE = 'VIEW_PROFILE';
export const VIEW_PROFILE_ERROR = 'VIEW_PROFILE_ERROR';
export const EDIT_PROFILE = 'EDIT_PROFILE';
export const EDIT_PROFILE_ERROR = 'EDIT_PROFILE-ERROR';

export const GET_PAGE_DETAILS = 'GET_PAGE_DETAILS';
